---
- hosts: localhost
  tasks:
    # task 1
    - name: ansible.builtin.ping
      ping:
      register: message

    # task 2
    - name: ansible.builtin.debug
      debug:
        msg: "{{ message }}"
